CREATE TABLE ARTICLES (
  ID  INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(20)
);

CREATE TABLE PARAGRAPHE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  CONTENT VARCHAR(60000),
  POSITION INT,
  ARTICLE_ID INT,
  FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ID)
);

INSERT INTO ARTICLES (TITLE) VALUE ('Article 1');
INSERT INTO ARTICLES (TITLE) VALUE ('Article 2');
INSERT INTO ARTICLES (TITLE) VALUE ('Article 3');
INSERT INTO ARTICLES (TITLE) VALUE ('Article 4');
INSERT INTO ARTICLES (TITLE) VALUE ('Article 5');